---
services:
  - docker
language: go
go:
  - 1.16.2
env:
  global:
    - secure: 3Ty8rsDZGvLT+aTSRlPIWYfdtuORDaQn8pc5SmNEwdFzLdUX6Cc+rr2mss3v25VS79MYqvfyuPmFHY40qJrSPd7TcD39vjNa6e/xwW3mNyvn9bNzA4DRuVQfYGrZk7mKz6+I480S/md9PKdD5dcJc8Fdy2WLWxCUODovempNfoBqZW4zKdpmKSQPp7fOn+ZjEaonGUVLShgv14aJKmpNi3A+bjgMe+/A6507xc6gFjEM6ctdoyNRd82Sp/P+z2Hg8wxo3BX45oVPEwOEZyxUUBykxkO1hLRxyQL0oo8ydkGCLM5MYE2Pq8xB6jdnq5X0aZl9b+SNagqDTIaOi1DXq0jxyRlx20UcwYl0ntDdc/8XMuNmIsen/JYeGolTuP31SAw9vlBpC58Rf6XPjhydhJz/3kjwRB3txuqI3D9cl2Qin+5f4bpvUa9s10WxwV5E+OaJCl356T6yItNEsUgwrcO60v/OTcf/q5sGcCaydsFgEWIlVdqFYVS7IMkEn6KkyMKZlTwsO5gdRKrtduMu1mdMmqa1mK6kryZ7q6ZB5ZsjCcPmM8afcSQUiTR0QdiBi/RpCJ0RKQ6fwDoGulSSn1UCsvGHipki81iXii+xq9VMIKFQ6yEr1oY5Esa27cuTv+asOOL9L/ZeBjpZaxXGnknOa5qS6+Gk3Ei96yLBsVc=
    - secure: q4cht4/gmKy29a82YNYc6xGyO6BaiISiVH3/T1smkN4wuqBg4aaufgpcUWSX5tHz3Uiqi3bKgfsMydueM06IYbF0hKiTpf71/BwzaoV+baLBRrrpzWAIzQb59E1jEkAtszV2Av4xt4sq7VjoN4SiQka/j42KZK+b3lsOMeDvXy7HIYKMHYo4sT0t3+OOMICK1Dmaox8KZIABQqAP6rh1CY0fyB/wMEYHozGHlBtpyINSq+VTiQspf7kUHbC2CBg+7/XIBLOsrRXPgzVBWYndagX6XSFW+13UY25/LZnZ3BS3rt9nSE0Qv//XkU8Ei+tLcL6YDPcNN1jiknuB5b6tBttJ22klTpHLkpyplhGnpSj9okLoedK0E5Ma59ikVQRePOPRM/Ge6LRzEkgK8O/4EdbH8fFaVyw9qiL6D6p/aZQb3gUWtZFTPufliYxCzGs8RL2uN3C7fOtgg79JZS74jskMsIDiHO/o+mLca9TsIBZs5DPrstrCY+cLe7QHdwNCSmIyD8H6S86mac0RFDeGSUYMgq+7lw4Z2sUpWe0pqAmwz0jK2c6iTNzokfxq7ewS6QBI5n48xQzgP67EIICYDP15/epb5JupnNDbQ/zCtDWSdYvbYjUe03eipADfgrkYDNht63Q5KuMJR+MEs0itYl/3OnTB9+sOnphANyGjwZg=
script:
  - GOOS=linux GOARCH=amd64 make dist
  - GOOS=darwin GOARCH=amd64 make dist
  - GOOS=freebsd GOARCH=amd64 make dist
  - GOOS=windows GOARCH=amd64 make dist
  - make docker-login
  - make docker-build
deploy:
  - provider: script
    script: make docker-release
    on:
      repo: imkira/gcp-iap-auth
      tags: true
  - provider: releases
    api_key:
      secure: yA9FlzerU/gUbhHjkoVll8rXQc9ICCXllN5ZiUEFSvKwBKfU3swbgf6t8tx4bcgxuP0Y6jDXRLgd0p60lSQXua2s+r0ccwudeRoH2xmUursRkjY21mILX2JHiK3cNHOEa6Uqwcpl/M0yzhJ4UnvP0tBV6Ci+kNfeZYYtX0DhcTasscCPIFaxInLv7dP3GC1X0abohiggJLcV2mZUy3hg6+SuvJSnRWjyheUHMYQN/muZE//XAPVcBOzZhJssSbsH2dLajWQO69pT72M84TrLZgcoWiXSbb4M5P54nsDxVRWc1+pcOmvpisvenH/jaS1PWZkCQF5tYXZZ6zfjrYv7nK/g+OryEWCiDsCKrYpVM/neNbhCklWPRdxCWVqgXs6Y0fRvkAlHutFEs97l8hJHmoCnvNngz3NCaG/3kKuTDlEP7cukjsUvWykaTmn6ejXX9CYbixIQl2ayJqfRpDR/1YZOAMWT2Ub0rv3uSKeCR7m/wTUSseulqwaBfrvHyp++M6jRVRrTuB9ptMA4GcvEMpGX3v+1qp5c431dMK7cxaEwN3nCVrEFYEK+uGk2IixECPxs320rhq9s9o/2aSl6SgfveIi6qCKV9OGN3zBTHOBCnyh8QF610yOSybFk5hAQsCC9l150ZJyJebWOTXKypMwR9POeFflTMYJFSfEpEB0=
    file_glob: true
    file:
      - dist/*
    skip_cleanup: true
    on:
      repo: imkira/gcp-iap-auth
      tags: true
